### ISSUE TITLE
Previewing the theme without prior installation (using grub2-theme-preview)

### ISSUE THREAD

**Issue by hartwork** [ThorstenS-linux/grub-thm-wks#1]
Hi @ThorstenS-linux ,

I ran into this theme while searching for use of `--class shutdown` in the wild. I noticed your screenshot uses QEMU. Have you been using [grub2-theme-preview](https://github.com/hartwork/grub2-theme-preview) in the process? If not, I wanted to bring it to your attention. Would you be interested in adding mention of `grub2-theme-preview` to the documentation somewhere, to ease preview to future users of your theme? PS: If this ticket feels like spam to you, please let me know and we can close this issue no problem.

Thanks and best, Sebastian

**Comment by ThorstenS-linux** [comment]
Hi Sebastian,
thanks for your ticket! I wasn`t aware of [grub2-theme-preview](https://github.com/hartwork/grub2-theme-preview) and will use it in future.

with best regards
/thorsten
